version: '3.4'

services:
  consolebinansews:
    image: ${DOCKER_REGISTRY-}consolebinansews
    build:
      context: .
      dockerfile: ConsoleBinanseWS/Dockerfile
    env_file:
        - .env
    volumes:
        - ./.env:/app/.env